### ISSUE TITLE
[Release] Prepare release 0.0.0

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#11]
## Overview

* prepare to release 0.0.0

## Tasks

  - [x] use by npm link from application
  - [x] exports in `lib/index.js`
  - [x] README.md
  
 ## Release

* `package.json`
  - [x] `files` parameter in `package.json`
  - [x] main
  - [x] version 0.0.0

* npm
  - [x] #17
