### ISSUE TITLE
⚒ Declare `EnvironmentResolver` as stub

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#125]
## Overview

Declare EnvironmentResolver as stub

## Tasks

- [x] Define to keep `#loadedDotenv`
- [x] Define to keep `#processEnv`
- [x] Define `EnvironmentResolver.create()`
