### ISSUE TITLE
✅ Enhance `EnvironmentResolver` convinient members to check `NODE_ENV`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#136]
## Overview

* Enhance `EnvironmentResolver` convinient members to check `NODE_ENV`

## Tasks

- [ ] ⚒ define `EnvironmentResolver#isDevelopment()`
- [ ] ⚒ define `EnvironmentResolver#isLive()`
- [ ] ⚒ define `EnvironmentResolver#isProduction()`
- [ ] ⚒ define `EnvironmentResolver#isStaging()`
- [ ] ⚒ define `EnvironmentResolver#isPreProduction()` (= means `#isNotProduction()`)
