### ISSUE TITLE
🧹 Uninstall `@openreachtech/renchan-test-tools`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#148]
## Overview

* Uninstall `@openreachtech/renchan-test-tools`

## Tasks

- [x] Uninstall `@openreachtech/renchan-test-tools`
- [x] Purge unnecessary `require()`
- [x] Fix test for `EnvironmentResolver` with `globalThis.constructorSpy`
