### ISSUE TITLE
⚙️ Setup dual package

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#185]
## Overview

* Setup dual package

## Tasks

- [x] Add `index.mjs`
- [x] ~Update `eslint.config.js` to add `index.mjs` to `ignores` field~
- [x] Add `exports` field in `package.json`
