### ISSUE TITLE
[Fix] ESLint rules

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#19]
## Overview

* 自社標準の dotfiles で `.eslintrc.yml` が変わったので、其の対応をします。

## Tasks

- [x] `no-unneeded-ternary`

    ```
    -  no-unneeded-ternary: error
    +  no-unneeded-ternary:
    +    - error
    +    - defaultAssignment: false
    ```
    
- [x] `semi-spacing`

    ```
      semi-spacing:
         - error
    -    - after: true
    -      before: false
    +    - before: false
    +      after: true
    ```
    
- [x] remove `valid-jsdoc`
- [x] add `jsdoc/xxxx`
