### ISSUE TITLE
[Environment] Setup Jest

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#2]
## Overview

* Setup Jest.

## Tasks

- [x] npm install jest @types/jest
- [x] `jest.config.js`
- [x] Update scripts.test in package.json.
- [x] sample test.
