### ISSUE TITLE
🚀 Publish `1.0.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#200]
## Overview

* Publish version as `1.0.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #204
- [x] Publish by procedure
- [x] #214
- [x] Push version tag `1.0.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `24054b8`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/renchan-env@1.0.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                   
  npm notice 3.0kB README.md                 
  npm notice 327B  index.js                  
  npm notice 120B  index.mjs                 
  npm notice 278B  lib/_.js                  
  npm notice 2.0kB lib/DotenvLoader.js       
  npm notice 3.7kB lib/EnvironmentFacade.js  
  npm notice 2.5kB lib/EnvironmentResolver.js
  npm notice 1.1kB package.json              
  npm notice 161B  scripts/env.js            
  npm notice 143B  scripts/env.mjs           
  npm notice 446B  types/index.d.ts          
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/renchan-env              
  npm notice version:       1.0.0                                   
  npm notice filename:      openreachtech-renchan-env-1.0.0.tgz     
  npm notice package size:  4.7 kB                                  
  npm notice unpacked size: 14.8 kB                                 
  npm notice shasum:        4fed9c8db64952c5348f4a9b2e04d7523b54a333
  npm notice integrity:     sha512-rf6HElCO6bqNp[...]p+jsEmu4o2xQg==
  npm notice total files:   12                                      
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/renchan-env@1.0.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing
  - target commit as: `24054b8`
  - node version: `v20.14.0`
  - npm version: `10.5.2`

- [x] Publish

  ```console
  git status
  git diff 24054b8
  ```

  ```console
  npm publish --access public
  ```
