### ISSUE TITLE
🚀 Publish `1.0.1`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#221]
# Details

* Publish version as `1.0.1`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

# Tasks

- [x] #222
- [x] Publish by procedure
- [x] #227
- [x] Push version tag `1.0.1` on main
- [x] Confirm access right of published package

# npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

# Procedure to Publish

## 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `07c9f64`

## 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

## 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [ ] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice
  npm notice 📦  @openreachtech/renchan-env@1.0.1
  npm notice Tarball Contents
  npm notice 1.1kB LICENSE
  npm notice 3.0kB README.md
  npm notice 327B index.js
  npm notice 120B index.mjs
  npm notice 278B lib/_.js
  npm notice 2.0kB lib/DotenvLoader.js
  npm notice 3.7kB lib/EnvironmentFacade.js
  npm notice 2.5kB lib/EnvironmentResolver.js
  npm notice 1.1kB package.json
  npm notice 161B scripts/env.js
  npm notice 143B scripts/env.mjs
  npm notice 446B types/index.d.ts
  npm notice Tarball Details
  npm notice name: @openreachtech/renchan-env
  npm notice version: 1.0.1
  npm notice filename: openreachtech-renchan-env-1.0.1.tgz
  npm notice package size: 4.7 kB
  npm notice unpacked size: 14.9 kB
  npm notice shasum: 306694a57f9d60713d1affb16065bbb746609b16
  npm notice integrity: sha512-asRjqQdFdLved[...]2IXw94914m8YQ==
  npm notice total files: 12
  npm notice
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/renchan-env@1.0.1
  ```

- [x] Check log of `--dry-run` by other member before actual publishing
  - target commit as: `07c9f64`
  - node version: `v20.14.0`
  - npm version: `10.9.0`

- [x] Publish

  ```console
  git status
  git diff 07c9f64
  ```

  ```console
  npm publish --access public
  ```

## 4. Confirm Access Right of Published Package

- When public module, check by installing package
- When ORT private module, check it below in package page

  ```
  https://github.com/orgs/openreachtech/packages/npm/__package__name__/settings
  ```

**Comment by EG-easy** [comment]
@StewEucen 

My result of `npm publish --dry-run`

```
$ npm publish --dry-run
npm notice 
npm notice 📦  @openreachtech/renchan-env@1.0.1
npm notice === Tarball Contents === 
npm notice 1.1kB LICENSE
npm notice 3.0kB README.md
npm notice 327B  index.js
npm notice 120B  index.mjs
npm notice 278B  lib/_.js
npm notice 2.0kB lib/DotenvLoader.js
npm notice 3.7kB lib/EnvironmentFacade.js
npm notice 2.5kB lib/EnvironmentResolver.js
npm notice 1.1kB package.json
npm notice 161B  scripts/env.js
npm notice 143B  scripts/env.mjs
npm notice 446B  types/index.d.ts
npm notice === Tarball Details ===
npm notice name:          @openreachtech/renchan-env
npm notice version:       1.0.1
npm notice filename:      openreachtech-renchan-env-1.0.1.tgz
npm notice package size:  4.7 kB
npm notice unpacked size: 14.9 kB
npm notice shasum:        306694a57f9d60713d1affb16065bbb746609b16
npm notice integrity:     sha512-asRjqQdFdLved[...]2IXw94914m8YQ==
npm notice total files:   12
npm notice
npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
+ @openreachtech/renchan-env@1.0.1
```

**Comment by StewEucen** [comment]
Publish `1.0.1`

https://github.com/openreachtech/renchan-env/pkgs/npm/renchan-env/295551048
