### ISSUE TITLE
⚙️ Update dependency packages to latest

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#223]
# Note

Current dependency packages

```
  "dependencies": {
    "dotenv": "^16.0.0"
  },
  "devDependencies": {
    "@openreachtech/eslint-config": "^3.0.2",
    "@openreachtech/jest-constructor-spy": "^1.1.0",
    "@types/jest": "^27.4.1",
    "eslint": "^9.4.0",
    "jest": "^27.5.1"
  }
```

# Tasks

- [x] ⚙️ Update `dotenv` version to `16.4.5`
- [x] ⚙️ Update `eslint` version to `9.13.0`
- [x] ⚙️ Update `jest` version to `29.7.0`
- [x] ⚙️ Update `@types/jest` version to `29.5.14`
