### ISSUE TITLE
[Environment] Update `.eslintrc.yml` from dotfiles

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#26]
## Overview

* Update `.eslintrc.yml` from dotfiles.

* See: https://github.com/openreachtech/dotfiles/blob/main/dotfiles/.eslintrc.yml

* This issue will be done after the other ESLint rules have been merged in dotfiles.
    > dotfiles で、他の ESLint ルールがマージされた後に実施します。

* Keep version `0.0.0`.
    
## Tasks

- [x] Update `.eslintrc.yml`
- [x] Remove `eslint-plugin-openreachtech` from dependences in package.json
- [x] Update `package-lock.json`
