### ISSUE TITLE
[Environment] update `.eslintrc.yml` with `@openreachtech/eslint-config`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#28]
## Overview

* Update `.eslintrc.yml` with `@openreachtech/eslint-config`.

* after finished https://github.com/openreachtech/eslint-config-openreachtech/issues/8

## Tasks

- [x] uninstall for ESLint packages
- [x] install ESLint with plugins of `jsdoc` and `@openreachtech/eslint-config`
- [x] replace `.eslintrc.yml` from dotfiles.
