### ISSUE TITLE
[Environment] Setup ESLint

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#5]
## Overview

* Setup ESLint.

## Tasks

- [x] npm install eslint
- [x] eslint --init
- [x] `.eslintrc.yml`
- [x] ESLint error sample code
- [x] Apply `no-else-if`
