### ISSUE TITLE
[Feature] Implement `Env`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#9]
## Overview

* Implement `Env` as in-house library.

## Spec

* If possible, the member to be obtained from an instance of Env should be a getter.
  > 可能であれば、Env のインスタンスから取得するメンバは getter とする。

## Tasks

* Design
  - [x] `DotenvLoader`
    - [x] `.resolvePath()`
      - `.config({ path: 'xxx' })` を使って、NODE_ENV 毎に解決する。
      - NODE_ENV が development 以外はディフォルト path とする。
  - [x] manage `process.env`
  - [x] manage `.env` by `dotenv`
  - [x] thows exception on access unknown property 
  [dotenv - npm](https://www.npmjs.com/package/dotenv)
  - [x] ~~Singleton Pattern~~
  - [x] ~~Utility to define property as getter~~
    > ~~property を getter として定義するユーティリティ~~

* Methods
  - [x] constructor
  - [x] `.create()`

* Usage
  - [x] AppEnv
  - [x] typedEnv
