### ISSUE TITLE
🧹 Tidy up `README.md`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-env#98]
## Overview

* Tidy up `README.md`

## Note

```
- Create `.npmrc` on application project root if not exeists.
+ Create `.npmrc` on application project root if not exists.
```

## Tasks

- [x] Fix typo `exeists` to `exists`
- [x] Fix type `Sapmle code.` to `Sample code.`
- [x] Purge `uhyouhyo` with `hash-of-api-key`
